config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :flights, only: [:index, :show] do
        resources :bookings, only: [:index, :show]
      end
    end
  end

  resources :flights, only: [:index]
  resources :bookings, only: [:create, :show, :new]
  # root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, class_name: "Flight", foreign_key: "finish"
  has_many :departing_flights, class_name: "Flight", foreign_key: "start"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: "start"
  belongs_to :to_airport, class_name: "Airport", foreign_key: "finish"
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings, inverse_of: :passengers
  has_many :flights, through: :bookings

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < ApplicationController
  before_action :find_booking, only: :show

  def index
    @bookings = Booking.all

    render json: @bookings
  end

  def show
    render json: @booking
  end

  private

    def find_booking
      @booking = Booking.find(params[:id])
    end

end

app/controllers/api/v1/flights_controller.rb
class Api::V1::FlightsController < ApplicationController
  before_action :find_flight, only: :show

  def index
    @flights = Flight.all

    render json: @flights
  end

  def show
    render json: @flight
  end

  private

    def find_flight
      @flight = Flight.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new #build via the flight params
    @booking = Booking.new
    @flight = Flight.find(params[:booking][:flight_id])
    @num_passengers = params[:booking][:passengers].to_i
    @num_passengers.times do
      @booking.passengers.build
    end

  end

  def create
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.thank_you(passenger, @flight).deliver_now!
      end
      redirect_to @booking
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

    def booking_params
      params.require(:booking).permit(:flight_id, :passengers, passengers_attributes: [:name, :email])
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include FlightsHelper

  def index
    @airports = Airport.all.map{ |x| [x.code, x.id] }
    @dates = Flight.all.map{ |x| [x.departure.strftime("%Y-%m-%d")] }
    @passengers = [[1], [2], [3], [4]]

    if params[:flight]
      @results = Flight.where(["start = ? AND finish = ? AND departure = ?", flight_params[:from_airport], flight_params[:to_airport], flight_params[:departure]])
      @num_pass = flight_params[:passengers]
      @booking = Booking.new
    end

  end

  private

    def flight_params
      params.require(:flight).permit(:id, :from_airport, :to_airport, :departure, :passengers)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def available_flights?
    !params[:flight].nil? && !@results.nil?
  end

  def no_results?
    params[:flight] && @results.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/new.html.erb
<div class="container index-header">
  Your Flight Information:
</div>
<div class="container-index-header">
  <p class="summary"><%= "Flight from: #{@flight.from_airport.code} to #{@flight.to_airport.code} on #{@flight.departure} for #{@passengers} people" %></p>
  <p class="summary">Please enter your passenger information below:</p>
</div>

<div class="index-container">
  <div class="booking-form">
    <%= form_for @booking do |f| %>
      <%= f.hidden_field(:flight_id, value: @flight.id) %>
      <%= f.fields_for :passengers do |passenger| %>
        <em>Passenger Information</em>
        <div class="passenger">
          <div class="passenger-name">
            <%= passenger.text_field :name, placeholder: "Name", class: "form-control" %>
          </div>
          <div class="passenger-email">
            <%= passenger.email_field :email, placeholder: "Email", class: "form-control" %>
          </div>
        </div>
      <% end %>
      <%= f.submit "Book your Flight!", class: "btn btn-primary booking-btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<!-- <div class="index-container">
  <h1 class="page-header">Your flight has been booked!</h1>
  <h4><%#= "Flight from: #{@booking.flight.from_airport.code}" %></h4>
  <h4><%#= "To: #{@booking.flight.to_airport.code}" %></h4>
  <h4><%#= "Leaving on: #{@booking.flight.departure}" %></h4>
  <p class="info">
    Passenger Information:
    <ul>
      <%# @booking.passengers.each do |passenger| %>
        <li>Name: <%#= passenger.name %></li>
        <li>Email: <%#= passenger.email %></li>
        <hr>
      <%# end %>
    </ul>
  <p>
  <%#= link_to "Back to Flight Search", flights_url, class: "btn btn-primary" %>
</div> -->

<div class="container index-header">
  Your flight has been booked!
  <hr />
</div>
<div class="booking-container">
  <div class="info-recap">
    <h4><%= "Flight from: #{@booking.flight.from_airport.code}" %></h4>
    <h4><%= "To: #{@booking.flight.to_airport.code}" %></h4>
    <h4><%= "Departing on: #{@booking.flight.departure}" %></h4>
  </div>
  <div class="passengers-info">
    Passengers:
    <ul>
      <% @booking.passengers.each do |passenger| %>
        <div class="passenger-recap">
          <li>Name: <%= passenger.name %></li>
          <li>Email: <%= passenger.email %></li>
        </div>
        <hr />
      <% end %>
    </ul>
  </div>
  <%= link_to "Back to Flight Search", flights_url, class: "btn btn-primary back-btn" %>
</div>

app/views/flights/_results.html.erb
<%= form_for(:booking, url: new_booking_url, method: :GET) do |f| %>

  <h3 class="flight-results">Search Results:</h3>

  <%= f.hidden_field(:passengers, value: @num_pass) %>
  <% @results.each do |result| %>
    <%= f.radio_button(:flight_id, result.id) %>
    <%= f.label(:flight_id, "#{result.from_airport.code} --> #{result.to_airport.code} on #{result.departure}") %>
  <% end %>
  <%= f.submit "Book this Flight", class: "btn btn-sm btn-primary" %>

<% end %>

app/views/flights/index.html.erb
<div class="container index-header">
  Book a Flight!
</div>
<div class="index-container">
  <div class="index-container-left">
    <div class="jumbotron flight-form">
      <%= form_for(:flight, url: flights_path, method: :GET) do |f| %>
        <div class="form-select mb-3">
          <strong>From:</strong> <%= f.select(:from_airport, options_for_select(@airports)) %>
        </div>
        <div class="form-select mb-10">
          <strong>To:</strong> <%= f.select(:to_airport, options_for_select(@airports)) %>
        </div>
        <div class="form-select mb-3">
          <strong>Date of Flight:</strong> <%= f.select(:departure, options_for_select(@dates)) %>
        </div>
        <div class="form-select mb-3">
          <strong>Passengers:</strong> <%= f.select(:passengers, options_for_select(@passengers)) %>
        </div>
        <%= f.submit "Search Flights", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="index-right">
    <% if @results %>
      <%= render 'results' %>
    <% elsif no_results? %>
      <p class="lead">No Flights found that match your criteria.</p>
    <% end %>
  </div>
</div>

app/views/home/home.html.erb
<div class="home-container">
  <div class="jumbotron">
    <h1 class="display-4">Welcome To Flight Booker!</h1>
    <p class="lead">A lightweight and minimal way to book your next amazing vacation!</p>
    <hr class="my-4">
    <p class="lead">Click the button below to start your next adventure!</p>
    <%= link_to "Get Started!", flights_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#= render 'shared/nav' %>
    <div class="container layout-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="container">
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1"><%= link_to "Speedy Flights", flights_path %></span>
    </div>
  </nav>
</div>